name: 2026-ct-wsi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - numpy
  - pillow
  - tqdm
  - imagecodecs
  - pip:
      - timm
      - huggingface_hub
      - safetensors
      - openslide-python
